name: UnioStats
main: me.uniodex.uniostats.UnioStats
author: 'UnioDex'
version: 1.0

softdepend: [MythicMobs, PlaceholderAPI]

commands:
  uniostats:
    description: UnioStats
    aliases: [stats, istatistikler]